name: CI

on:
  push:
  pull_request:
  release:
    types:
    - created

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        path: robotraconteur_companion_python
    - name: robotraconteur ppa
      run: |
        sudo add-apt-repository -y ppa:robotraconteur/ppa
        sudo apt-get update
    - name: apt install
      run: >
        sudo apt-get install python3-robotraconteur python3-pytest python3-numpy
        python3-yaml python3-setuptools python3-wheel
    - name: python pip
      run: python3 -m pip install --user ./robotraconteur_companion_python
    - name: python pytest
      run: python3 -m pytest robotraconteur_companion_python/test -s
  main-pythonver:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
      with:
        path: robotraconteur_companion_python
    - uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python_version}}'
    - name: upgrade python pip
      run: python -m pip install --upgrade pip
    - name: python pip
      run: python -m pip install --user ./robotraconteur_companion_python
    - name: python pytest
      run: python -m pytest robotraconteur_companion_python/test -s
  pre-commit:
    runs-on: ubuntu-22.04
    env:
      SKIP: no-commit-to-branch
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: apt
      run: |
        sudo apt update
        sudo apt install -y dos2unix
    - uses: pre-commit/action@v3.0.1
